FROM python:3.9-slim

WORKDIR opt/app

RUN apt-get update
RUN pip install --upgrade pip

COPY RestAPI/requirements_api.txt .

RUN pip install --no-cache-dir -r requirements_api.txt

COPY RestAPI/repository.py .
COPY RestAPI/service.py .
COPY RestAPI/controller.py .

EXPOSE 1488

ENTRYPOINT ["python", "controller.py"]
